BIN := calc
SOURCE := calc.c
HEADERS := calc_sum.h calc_sub.h calc_multi.h calc_division.h
.PHONY := clean


$(BIN): $(SOURCE)
		gcc -o $(BIN) $(SOURCE)

$(BIN): $(HEADERS)

$(.PHONY):
		rm -rf $(BIN)








